name: 'Terraform AWS Deploy'

on:
  # ✅ Manual Trigger Added
  workflow_dispatch

permissions:
  id-token: write # Required for requesting the OIDC token
  contents: read  # Required for checking out the code

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    
    # Maps your GitHub password secret directly to a Terraform variable
    env:
      TF_VAR_vm_password: ${{ secrets.VM_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # role-to-assume: arn:aws:iam::572556120615:role/Git_admin # Double check this ARN string!
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

        # ADD THIS DEBUG STEP:
      - name: Ask AWS what is Free Tier Eligible
        run: aws ec2 describe-instance-types --filters Name=free-tier-eligible,Values=true --query "InstanceTypes[*].InstanceType" --region ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan